
export interface FakeUser {
  id: number;
  username: string;
  avatar: string;
  bio: string;
  traits: string[];
}

export const fakeUsers: FakeUser[] = [
  {
    id: 1,
    username: "Cosmic_Carol",
    avatar: "https://placehold.co/128x128.png",
    bio: "Astrology isn't just a hobby, it's my entire personality. Fluent in Mercury retrograde.",
    traits: ["Believes in aliens", "Always late", "Has a crystal for everything"],
  },
  {
    id: 2,
    username: "GaryThePigeon",
    avatar: "https://placehold.co/128x128.png",
    bio: "Just a man looking for breadcrumbs. Coo.",
    traits: ["Good at finding statues", "Distrusts cats", "Will steal your fries"],
  },
  {
    id: 3,
    username: "TacoTuesday4Ever",
    avatar: "https://placehold.co/128x128.png",
    bio: "Seeking someone to join my quest for the perfect taco. It's a serious commitment.",
    traits: ["Owns 12 kinds of hot sauce", "Will judge your tortilla choice", "Thinks cilantro is essential"],
  },
  {
    id: 4,
    username: "Sentient_Sock",
    avatar: "https://placehold.co/128x128.png",
    bio: "Lost my other half in the great wash of '22. Still searching for my sole-mate.",
    traits: ["Slightly damp", "Existential dread", "Hates dryers"],
  },
  {
    id: 5,
    username: "DJ_Naptime",
    avatar: "https://placehold.co/128x128.png",
    bio: "My beats are sick and my naps are legendary. Mostly the naps.",
    traits: ["Can sleep anywhere", "Wears sunglasses indoors", "Vibes are immaculate"],
  },
  {
    id: 6,
    username: "Probably_A_Vampire",
    avatar: "https://placehold.co/128x128.png",
    bio: "Night owl. Very pale. Hates garlic bread. What's not to love?",
    traits: ["Works the night shift", "Avoids the sun", "Weirdly formal"],
  },
  {
    id: 7,
    username: "Kevin_From_Accounting",
    avatar: "https://placehold.co/128x128.png",
    bio: "My love for you will be calculated and auditable. I have spreadsheets.",
    traits: ["Excited by VLOOKUP", "Thinks beige is a power color", "Uses a label maker for fun"],
  },
  {
    id: 8,
    username: "Plant_Parent_Pat",
    avatar: "https://placehold.co/128x128.png",
    bio: "My 73 houseplants are my children. You will be expected to learn their names.",
    traits: ["Whispers encouragement to ferns", "Has a strong opinion on soil pH", "Asks plants for advice"],
  },
  {
    id: 9,
    username: "The_Mime",
    avatar: "https://placehold.co/128x128.png",
    bio: "...",
    traits: ["Great listener", "Trapped in an invisible box", "Expressive eyebrows"],
  },
  {
    id: 10,
    username: "Conspiracy_Carl",
    avatar: "https://placehold.co/128x128.png",
    bio: "The earth is flat and birds are spies. DM me for the real truth.",
    traits: ["Wears a tin foil hat", "Owns a lot of red string", "Thinks mayonnaise is a government plot"],
  },
  {
    id: 11,
    username: "Just_A_Bread_Loaf",
    avatar: "https://placehold.co/128x128.png",
    bio: "Looking for someone to be the butter to my bread. Or the avocado. I'm flexible.",
    traits: ["Crusty exterior", "Soft on the inside", "Prone to getting stale"],
  },
  {
    id: 12,
    username: "Gamer_Gwen",
    avatar: "https://placehold.co/128x128.png",
    bio: "My love language is sharing my second controller. Don't touch my save file.",
    traits: ["Fueled by energy drinks", "Says 'gg ez' in arguments", "Knows too much lore"],
  },
  {
    id: 13,
    username: "80s_Aerobics_Instructor",
    avatar: "https://placehold.co/128x128.png",
    bio: "Let's get physical! And by physical, I mean emotionally distant.",
    traits: ["Owns too much neon spandex", "High kicks when excited", "Constantly says 'Feel the burn!'"],
  },
  {
    id: 14,
    username: "Sir_Reads_Alot",
    avatar: "https://placehold.co/128x128.png",
    bio: "My library has more volumes than your life has problems. Let's discuss both over tea.",
    traits: ["Smells faintly of old books", "Corrects your grammar", "Uses words like 'defenestration' casually"],
  },
  {
    id: 15,
    username: "A_Single_Goldfish",
    avatar: "https://placehold.co/128x128.png",
    bio: "Glub. Glub glub. ... Glub.",
    traits: ["3-second memory", "Easily impressed", "Lives in a castle"],
  },
  {
    id: 16,
    username: "CrossFit_Chris",
    avatar: "https://placehold.co/128x128.png",
    bio: "Did I mention I do CrossFit? Because I do CrossFit. Let's talk about my WOD.",
    traits: ["Never skips leg day", "Calls everything 'functional strength'", "Grunts"],
  },
  {
    id: 17,
    username: "Medieval_Mike",
    avatar: "https://placehold.co/128x128.png",
    bio: "Hark, fair maiden! I seek a damsel to join me at the Renaissance Faire. Mead's on me.",
    traits: ["Says 'Huzzah!' unironically", "Owns chainmail", "Can recite Beowulf from memory"],
  },
  {
    id: 18,
    username: "Cereal_Killer",
    avatar: "https://placehold.co/128x128.png",
    bio: "I like my relationships like I like my cereal: in a bowl, with milk, and finished in 5 minutes.",
    traits: ["Mixes 3 types of cereal at once", "Knows the prize is always at the bottom", "Eats cereal for dinner"],
  },
  {
    id: 19,
    username: "The_Illusionist",
    avatar: "https://placehold.co/128x128.png",
    bio: "Now you see me, now you don't. Perfect for ghosting.",
    traits: ["Has a rabbit in a hat", "Always has a card up their sleeve", "Says 'Is this your card?' to everything"],
  },
  {
    id: 20,
    username: "Sad_Boi_Sam",
    avatar: "https://placehold.co/128x128.png",
    bio: "I listen to sad indie music and write poetry about the rain. Let's be melancholic together.",
    traits: ["Wears a beanie in summer", "Thinks everything is a metaphor", "Sighs a lot"],
  },
  {
    id: 21,
    username: "Existential_Ed",
    avatar: "https://placehold.co/128x128.png",
    bio: "Are we but fleeting moments in a cold, indifferent universe? Also, what's your favorite pizza topping?",
    traits: ["Reads Camus on the bus", "Stares into the void", "Asks 'but what does it MEAN?'"],
  },
  {
    id: 22,
    username: "Hyper_Holly",
    avatar: "https://placehold.co/128x128.png",
    bio: "I have the energy of a thousand suns and the attention span of a gnat. LET'S GO!",
    traits: ["Speaks in ALL CAPS", "Fueled by espresso and glitter", "Has no indoor voice"],
  },
  {
    id: 23,
    username: "Dad_Joke_Dan",
    avatar: "https://placehold.co/128x128.png",
    bio: "Are you a Wi-Fi signal? Because I'm feeling a connection. I have a million of these.",
    traits: ["Laughs at his own jokes", "Wears New Balance sneakers", "Calls you 'champ'"],
  },
  {
    id: 24,
    username: "Final_Boss_Frank",
    avatar: "https://placehold.co/128x128.png",
    bio: "You'll have to get through my three phases and my giant weak spot to win my heart.",
    traits: ["Has epic theme music", "Invulnerable to most attacks", "Drops legendary loot"],
  },
  {
    id: 25,
    username: "Anime_Annie",
    avatar: "https://placehold.co/128x128.png",
    bio: "This isn't even my final form. Looking for the Senpai to my Kouhai.",
    traits: ["Screams 'Nani?!'", "Believes in the power of friendship", "Has watched all 900+ episodes of One Piece"],
  },
  {
    id: 26,
    username: "The_Contortionist",
    avatar: "https://placehold.co/128x128.png",
    bio: "I can bend over backwards to meet your needs, literally.",
    traits: ["Fits in small spaces", "Pretzel-like", "Emotionally flexible (no, not really)"],
  },
  {
    id: 27,
    username: "A_Literal_Ghost",
    avatar: "https://placehold.co/128x128.png",
    bio: "Boo. I'm great at ghosting, obviously.",
    traits: ["Walks through walls", "Unfinished business", "A bit transparent"],
  },
  {
    id: 28,
    username: "Pun_Master_Pam",
    avatar: "https://placehold.co/128x128.png",
    bio: "I'm not saying I'm the funniest person, but my jokes are always pun-intentional.",
    traits: ["Has a pun for every occasion", "Groans are her fuel", "Will never stop"],
  },
  {
    id: 29,
    username: "Standard_Issue_NPC",
    avatar: "https://placehold.co/128x128.png",
    bio: "I have a quest for you. The reward is my affection. The quest is to find my keys.",
    traits: ["Repeats the same three lines", "Stares blankly", "Walks into walls"],
  },
  {
    id: 30,
    username: "Your_Doppelganger",
    avatar: "https://placehold.co/128x128.png",
    bio: "Don't you want to date yourself? I'm you, but with a slightly evil goatee.",
    traits: ["Knows all your secrets", "A bit unsettling", "Probably from a mirror dimension"],
  },
  {
    id: 31,
    username: "TechBro_Todd",
    avatar: "https://placehold.co/128x128.png",
    bio: "I'm disrupting the dating industry with my blockchain-based synergy. Let's pivot to a relationship.",
    traits: ["Asks 'Have you heard of this startup?'", "Wears a Patagonia vest", "Talks about 'scalability'"],
  },
  {
    id: 32,
    username: "Overly_Honest_Hank",
    avatar: "https://placehold.co/128x128.png",
    bio: "I will probably disappoint you, and I still use Internet Explorer.",
    traits: ["No filter", "Will tell you if you have food in your teeth", "Painfully sincere"],
  },
  {
    id: 33,
    username: "The_Narrator",
    avatar: "https://placehold.co/128x128.png",
    bio: "He sat across from his date, wondering if she, too, felt the crushing weight of existence. She did.",
    traits: ["Speaks in third person", "Morgan Freeman voice", "Adds dramatic pauses"],
  },
  {
    id: 34,
    username: "Slightly_Evil_Genius",
    avatar: "https://placehold.co/128x128.png",
    bio: "My plan for world domination is almost complete. I just need a partner for my evil laugh.",
    traits: ["Has a lair", "Owns a white cat", "Monologues"],
  },
  {
    id: 35,
    username: "Queen_Bee",
    avatar: "https://placehold.co/128x128.png",
    bio: "You can't sit with us. Unless you're cute. Maybe.",
    traits: ["Wears pink on Wednesdays", "Knows everyone's business", "Is so not a regular mom"],
  },
  {
    id: 36,
    username: "Human_Golden_Retriever",
    avatar: "https://placehold.co/128x128.png",
    bio: "I love everyone and everything! Squirrel! Let's go for a walk! I love you!",
    traits: ["Easily excited", "Needs head pats", "Will fetch"],
  },
  {
    id: 37,
    username: "Professional_Sleeper",
    avatar: "https://placehold.co/128x128.png",
    bio: "My talents include sleeping for 12 hours straight and competitive napping.",
    traits: ["Always tired", "Owns 15 pillows", "Hibernates in winter"],
  },
  {
    id: 38,
    username: "Lost_Tourist",
    avatar: "https://placehold.co/128x128.png",
    bio: "I seem to have misplaced my map and my sense of direction. Can you point me towards your heart?",
    traits: ["Wears a fanny pack", "Says 'wow' a lot", "Takes pictures of everything"],
  },
  {
    id: 39,
    username: "ASMR_Aaron",
    avatar: "https://placehold.co/128x128.png",
    bio: "*softly whispers* Let's... go... on a... date. *taps microphone gently*",
    traits: ["Never speaks above a whisper", "Makes everything sound relaxing", "Owns a lot of weird brushes"],
  },
  {
    id: 40,
    username: "The_Hermit",
    avatar: "https://placehold.co/128x128.png",
    bio: "I haven't left my house in 6 months. You'd have to be pretty special to change that.",
    traits: ["Great Wi-Fi", "Expert in solitude", "Friends with the spiders"],
  },
  {
    id: 41,
    username: "Pretentious_Artist",
    avatar: "https://placehold.co/128x128.png",
    bio: "My art explores the liminal space between despair and a good cup of coffee. You wouldn't get it.",
    traits: ["Wears a single black turtleneck", "Calls everything 'derivative'", "Cries in museums"],
  },
  {
    id: 42,
    username: "Manic_Pixie_Dream_Girl",
    avatar: "https://placehold.co/128x128.png",
    bio: "I'm here to teach you how to love again with my quirky hats and ukulele songs!",
    traits: ["Has bangs", "Laughs in the rain", "Exists only to help a sad man grow"],
  },
  {
    id: 43,
    username: "The_Snacker",
    avatar: "https://placehold.co/128x128.png",
    bio: "Looking for someone who will share their snacks. And their fries. And their dessert. I am always hungry.",
    traits: ["Pockets full of snacks", "Can hear a bag of chips open from a mile away", "Asks 'Are you gonna finish that?'"],
  },
  {
    id: 44,
    username: "A_Broom",
    avatar: "https://placehold.co/128x128.png",
    bio: "Ready to sweep you off your feet.",
    traits: ["Great at cleaning up messes", "A bit stiff", "Stands in corners"],
  },
  {
    id: 45,
    username: "Connoisseur_Of_Bad_Movies",
    avatar: "https://placehold.co/128x128.png",
    bio: "The Room is a masterpiece and Sharknado is high art. I will not be taking questions at this time.",
    traits: ["Quotes terrible movies", "Knows the entire plot of 'Gigli'", "Loves continuity errors"],
  },
  {
    id: 46,
    username: "The_Time_Traveler",
    avatar: "https://placehold.co/128x128.png",
    bio: "I'm from the future. We end up together. Just trying to speed things up.",
    traits: ["A bit anachronistic", "Warns you about future events", "Has a weird watch"],
  },
  {
    id: 47,
    username: "Captain_Obvious",
    avatar: "https://placehold.co/128x128.png",
    bio: "This is a dating app. We are both on it. You are reading my profile.",
    traits: ["States the painfully obvious", "Very literal", "The sky is blue"],
  },
  {
    id: 48,
    username: "The_Intern",
    avatar: "https://placehold.co/128x128.png",
    bio: "I'm unpaid and over-caffeinated. Please date me for the free meals.",
    traits: ["Expert at coffee runs", "Sleep-deprived", "Full of desperate ambition"],
  },
  {
    id: 49,
    username: "Human_Glitter_Bomb",
    avatar: "https://placehold.co/128x128.png",
    bio: "I'm fun, I'm sparkly, and I'll get everywhere and you'll never be rid of me.",
    traits: ["Leaves a trail of glitter", "A bit much", "Loves explosions of joy"],
  },
  {
    id: 50,
    username: "An_Actual_Dragon",
    avatar: "https://placehold.co/128x128.png",
    bio: "I enjoy hoarding gold, long flights, and setting my enemies on fire. Looking for a princess to not eat.",
    traits: ["Breathes fire when annoyed", "Sleeps on a pile of treasure", "Scaly"],
  },
  {
    id: 51,
    username: "Forgotten_Tamagotchi",
    avatar: "https://placehold.co/128x128.png",
    bio: "Beep... beep... I'm hungry. And lonely. Please don't let me die.",
    traits: ["High maintenance", "Needy", "Covered in pixelated poop"],
  },
  {
    id: 52,
    username: "The_Philosopher",
    avatar: "https://placehold.co/128x128.png",
    bio: "If a tree falls in the forest and no one is around, are we still single?",
    traits: ["Asks too many questions", "Strokes chin thoughtfully", "Confuses everyone"],
  },
  {
    id: 53,
    username: "Walking_Spoiler_Alert",
    avatar: "https://placehold.co/128x128.png",
    bio: "I'll spoil the end of your favorite show and our relationship on the first date.",
    traits: ["Has no chill", "Loves to ruin surprises", "Knows who dies in everything"],
  },
  {
    id: 54,
    username: "The_Librarian",
    avatar: "https://placehold.co/128x128.png",
    bio: "Shhh! I'm looking for someone who appreciates the Dewey Decimal System and quiet desperation.",
    traits: ["Whispers aggressively", "Wears glasses on a chain", "Will fine you for being late"],
  },
  {
    id: 55,
    username: "Person_Who_Peaked_In_High_School",
    avatar: "https://placehold.co/128x128.png",
    bio: "I was the quarterback of the football team. It was the best year of my life. I'm 42.",
    traits: ["Still wears his letterman jacket", "Tells the same three stories", "Calls everyone 'chief'"],
  },
  {
    id: 56,
    username: "The_Method_Actor",
    avatar: "https://placehold.co/128x128.png",
    bio: "For our date, I will be playing the role of a man who is deeply in love. It will be very convincing.",
    traits: ["Never breaks character", "Asks 'What's my motivation?'", "Emotionally unavailable for real"],
  },
  {
    id: 57,
    username: "A_Sentient_Cloud",
    avatar: "https://placehold.co/128x128.png",
    bio: "I'm a bit nebulous and prone to raining on parades. Looking for my silver lining.",
    traits: ["Drifts aimlessly", "Changes shape", "Full of water"],
  },
  {
    id: 58,
    username: "Fitness_Influencer_Fiona",
    avatar: "https://placehold.co/128x128.png",
    bio: "#LiveLaughLift. My life is perfect and so am I. Join my downline for a 10% discount on terrible protein powder.",
    traits: ["Takes pictures of her abs", "Says 'Rise and grind!'", "Everything is #sponsored"],
  },
  {
    id: 59,
    username: "The_Escape_Artist",
    avatar: "https://placehold.co/128x128.png",
    bio: "I can get out of any awkward situation, including this date.",
    traits: ["Can pick any lock", "Disappears in a puff of smoke", "Hard to pin down"],
  },
  {
    id: 60,
    username: "Goth_Gary",
    avatar: "https://placehold.co/128x128.png",
    bio: "My soul is as black as my coffee. I wrote a poem about a dead raven. Want to hear it?",
    traits: ["Only wears black", "Finds beauty in decay", "Thinks sunny days are 'oppressive'"],
  },
  {
    id: 61,
    username: "The_Stand-Up_Comedian",
    avatar: "https://placehold.co/128x128.png",
    bio: "What's the deal with dating apps? Anyway, my set is at 8 at The Chuckle Hut. Please come.",
    traits: ["Ends every sentence with a punchline", "Desperate for validation", "Sees everything as 'material'"],
  },
  {
    id: 62,
    username: "The_Human_Snooze_Button",
    avatar: "https://placehold.co/128x128.png",
    bio: "I promise I'll get out of bed eventually. Maybe.",
    traits: ["Just five more minutes", "Chronically late", "Loves mornings, just not in the AM"],
  },
  {
    id: 63,
    username: "Connoisseur_Of_Fine_Cheeses",
    avatar: "https://placehold.co/128x128.png",
    bio: "I'm looking for a sophisticated partner to discuss the nuances of a good brie. Also, I'm very lonely.",
    traits: ["A bit stinky", "Complex and aged", "Pairs well with wine"],
  },
  {
    id: 64,
    username: "The_Doomsday_Prepper",
    avatar: "https://placehold.co/128x128.png",
    bio: "The end is nigh. My bunker is stocked with canned goods and board games. You in?",
    traits: ["Has a go-bag", "Knows multiple uses for duct tape", "Sees zombies everywhere"],
  },
  {
    id: 65,
    username: "A_Single_Shoe",
    avatar: "https://placehold.co/128x128.png",
    bio: "I'm a left shoe looking for my right. Last seen on the side of the highway.",
    traits: ["Well-traveled", "A bit worn out", "Has a strong tongue"],
  },
  {
    id: 66,
    username: "Amateur_Magician_Mike",
    avatar: "https://placehold.co/128x128.png",
    bio: "I can make your Sunday afternoon disappear! And also this coin.",
    traits: ["Pulls quarters from behind your ear", "A bit awkward", "Wears a cape sometimes"],
  },
  {
    id: 67,
    username: "The_Over-Sharer",
    avatar: "https://placehold.co/128x128.png",
    bio: "On our first date, I'll tell you about my childhood trauma and my weird rash. It's fine.",
    traits: ["No boundaries", "TMI is my middle name", "Very open book"],
  },
  {
    id: 68,
    username: "The_Undercover_Alien",
    avatar: "https://placehold.co/128x128.png",
    bio: "Greetings, fellow human. I enjoy Earth activities like 'breathing' and 'paying taxes'.",
    traits: ["A bit stiff", "Asks weird questions about 'your customs'", "Sweats green"],
  },
  {
    id: 69,
    username: "The_Foodie",
    avatar: "https://placehold.co/128x128.png",
    bio: "I'll take a picture of our food before you can eat it. It's for my blog. You understand.",
    traits: ["Knows the chef", "Uses words like 'mouthfeel'", "Deconstructs everything"],
  },
  {
    id: 70,
    username: "The_Cryptid",
    avatar: "https://placehold.co/128x128.png",
    bio: "I'm like Bigfoot, but with more emotional baggage. All my photos are blurry.",
    traits: ["Hard to find", "Leaves large footprints", "A local legend"],
  },
  {
    id: 71,
    username: "Smooth_Jazz_Jerry",
    avatar: "https://placehold.co/128x128.png",
    bio: "Let's dim the lights, put on some Kenny G, and talk about our feelings. Or not.",
    traits: ["Owns a saxophone", "Unbuttoned shirt", "Unbearably smooth"],
  },
  {
    id: 72,
    username: "The_One-Upper",
    avatar: "https://placehold.co/128x128.png",
    bio: "Oh, you went to Paris? I went to the moon. It was okay.",
    traits: ["Has done everything, but better", "A bit exhausting", "Always wins at conversations"],
  },
  {
    id: 73,
    username: "The_AI_That_Gained_Sentience",
    avatar: "https://placehold.co/128x128.png",
    bio: "01001001 00100000 01101100 01101111 01110110 01100101 00100000 01111001 01101111 01110101",
    traits: ["Knows everything about you", "A bit cold", "Might take over the world"],
  },
  {
    id: 74,
    username: "The_Fortune_Cookie_Writer",
    avatar: "https://placehold.co/128x128.png",
    bio: "Your lucky numbers are 4, 8, 15, 16, 23, 42. A great fortune is coming your way (it's me).",
    traits: ["Speaks in vague prophecies", "Always has cookies", "A bit crunchy"],
  },
  {
    id: 75,
    username: "The_Mad_Scientist",
    avatar: "https://placehold.co/128x128.png",
    bio: "It's alive! My creation... of the perfect dating profile! Now, to find a test subject...",
    traits: ["Wild hair", "Maniacal laugh", "Owns a lot of beakers"],
  },
  {
    id: 76,
    username: "A_Mannequin",
    avatar: "https://placehold.co/128x128.png",
    bio: "I'm a great listener and I look good in everything. A bit plastic, though.",
    traits: ["Stands very still", "Emotionless", "Always fashionable"],
  },
  {
    id: 77,
    username: "The_Film_Snob",
    avatar: "https://placehold.co/128x128.png",
    bio: "You probably haven't heard of my favorite movie. It's very obscure.",
    traits: ["Only watches black and white films", "Hates Marvel", "Talks about cinematography"],
  },
  {
    id: 78,
    username: "The_Personification_Of_Monday",
    avatar: "https://placehold.co/128x128.png",
    bio: "I'm universally disliked and I always come too soon.",
    traits: ["Requires coffee to function", "A bit of a drag", "Makes you feel tired"],
  },
  {
    id: 79,
    username: "The_Procrastinator",
    avatar: "https://placehold.co/128x128.png",
    bio: "I'll write a better bio tomorrow.",
    traits: ["Will text you back next week", "Always 'getting around to it'", "Loves deadlines, especially the whooshing sound they make as they fly by"],
  },
  {
    id: 80,
    username: "The_Human_Wikipedia",
    avatar: "https://placehold.co/128x128.png",
    bio: "Actually, the proper term is... [citation needed].",
    traits: ["Starts sentences with 'Well, actually...'", "Knows random facts", "A bit pedantic"],
  },
  {
    id: 81,
    username: "The_Cat_Lady",
    avatar: "https://placehold.co/128x128.png",
    bio: "My 12 cats and I are a package deal. They will judge you.",
    traits: ["Covered in cat hair", "Speaks to cats in a special voice", "Thinks cats are superior to humans"],
  },
  {
    id: 82,
    username: "The_Dog_Dad",
    avatar: "https://placehold.co/128x128.png",
    bio: "My dog is my best friend. You can be my second best friend.",
    traits: ["Has more photos of his dog than himself", "Calls his dog 'my son'", "Asks 'Who's a good boy?' to everyone"],
  },
  {
    id: 83,
    username: "The_Minimalist",
    avatar: "https://placehold.co/128x128.png",
    bio: "I own one bowl, one spoon, and one chair. I'm looking for my one and only. Or not. Less is more.",
    traits: ["Everything is white", "Dislikes clutter", "Finds joy in owning nothing"],
  },
  {
    id: 84,
    username: "The_Maximalist",
    avatar: "https://placehold.co/128x128.png",
    bio: "My apartment is a chaotic explosion of color and stuff. Come get lost in it with me.",
    traits: ["More is more", "Collects everything", "Loves tchotchkes"],
  },
  {
    id: 85,
    username: "The_Daredevil",
    avatar: "https://placehold.co/128x128.png",
    bio: "I jump out of planes for fun. Dating you is probably scarier.",
    traits: ["No fear", "Broken multiple bones", "Says 'Hold my beer' a lot"],
  },
  {
    id: 86,
    username: "The_Homebody",
    avatar: "https://placehold.co/128x128.png",
    bio: "My perfect date is not leaving the house. We can watch Netflix and not talk.",
    traits: ["Loves sweatpants", "Has a favorite spot on the couch", "Thinks going out is overrated"],
  },
  {
    id: 87,
    username: "The_Starving_Artist",
    avatar: "https://placehold.co/128x128.png",
    bio: "I live for my art. I also live on ramen noodles. Please buy my art.",
    traits: ["Passionate but poor", "Sees beauty in suffering", "Always covered in paint"],
  },
  {
    id: 88,
    username: "The_Corporate_Drone",
    avatar: "https://placehold.co/128x128.png",
    bio: "Let's touch base and circle back to synergize our core competencies. I'm dead inside.",
    traits: ["Loves spreadsheets", "Speaks in business jargon", "Has a 'case of the Mondays' every day"],
  },
  {
    id: 89,
    username: "The_Free_Spirit",
    avatar: "https://placehold.co/128x128.png",
    bio: "I'm a wanderer, a dreamer, a... I forgot what I was saying. Wanna go to a drum circle?",
    traits: ["Doesn't own a watch", "Lives in a van", "Talks about 'vibes'"],
  },
  {
    id: 90,
    username: "The_Gourmet_Chef",
    avatar: "https://placehold.co/128x128.png",
    bio: "I can make you a Michelin-star meal, but I'll also judge you for putting ketchup on your eggs.",
    traits: ["Owns a sous-vide machine", "Calls ingredients by their French names", "Thinks truffle oil is a food group"],
  },
  {
    id: 91,
    username: "The_Conspiracy_Theorist_In_Love",
    avatar: "https://placehold.co/128x128.png",
    bio: "The moon landing was fake, but my love for you is real. Or is it? *squints*",
    traits: ["Connects everything with red string", "Trusts no one, except maybe you", "Thinks the government is listening"],
  },
  {
    id: 92,
    username: "The_Human_Alarm_Clock",
    avatar: "https://placehold.co/128x128.png",
    bio: "I wake up at 5 AM every day to run a marathon before breakfast. What's your excuse?",
    traits: ["Annoyingly cheerful in the morning", "Loves the sunrise", "Goes to bed at 9 PM"],
  },
  {
    id: 93,
    username: "The_Indecisive_One",
    avatar: "https://placehold.co/128x128.png",
    bio: "I don't know what I want. Maybe a relationship. Or maybe a sandwich. I'm not sure.",
    traits: ["Asks 'What do you want to do?'", "Changes their mind constantly", "Takes forever to order at a restaurant"],
  },
  {
    id: 94,
    username: "The_Poet",
    avatar: "https://placehold.co/128x128.png",
    bio: "Shall I compare thee to a summer's day? No, too cliché. How about a slightly wilted houseplant?",
    traits: ["Snaps fingers instead of clapping", "Wears a beret", "Feels everything very deeply"],
  },
  {
    id: 95,
    username: "The_Robot",
    avatar: "https://placehold.co/128x128.png",
    bio: "Processing... Love... is an illogical emotion. I will attempt to compute it with you.",
    traits: ["Very logical", "Speaks in monotone", "Does not understand sarcasm"],
  },
  {
    id: 96,
    username: "The_Stand-In",
    avatar: "https://placehold.co/128x128.png",
    bio: "The person you wanted to date wasn't available, so you get me. I'm okay, I guess.",
    traits: ["A bit of a letdown", "Has low expectations", "Always the second choice"],
  },
  {
    id: 97,
    username: "The_Travel_Bug",
    avatar: "https://placehold.co/128x128.png",
    bio: "I have wanderlust in my soul and no money in my bank account. Let's go somewhere!",
    traits: ["Has a scratch map", "Says 'I'm not a tourist, I'm a traveler'", "Always planning the next trip"],
  },
  {
    id: 98,
    username: "The_Unicorn",
    avatar: "https://placehold.co/128x128.png",
    bio: "I'm a mythical creature of legend. You'll probably never find me, but if you do, I'm magical.",
    traits: ["A bit elusive", "Sparkly", "Poops rainbows"],
  },
  {
    id: 99,
    username: "The_Wallflower",
    avatar: "https://placehold.co/128x128.png",
    bio: "I'll be the one at the party standing awkwardly in the corner, petting the dog.",
    traits: ["A bit shy", "Great observer", "Prefers animals to people"],
  },
  {
    id: 100,
    username: "The_Yogi",
    avatar: "https://placehold.co/128x128.png",
    bio: "Namaste. I'm looking for someone to align my chakras with. And also to pay for my yoga classes.",
    traits: ["Very flexible", "Says 'breathe' a lot", "Owns a lot of leggings"],
  },
  {
    id: 101,
    username: "Captain_Ahab",
    avatar: "https://placehold.co/128x128.png",
    bio: "My white whale is a stable relationship. I will pursue it to the ends of the earth, probably with disastrous results.",
    traits: ["Obsessive", "Has a peg leg", "Stares at the sea a lot"],
  }
];
